### PR TITLE
chore: Remove private randomness

### PR DESCRIPTION
**Pull request by Bexanderthebex**
attempts to fix https://github.com/drand/drand/issues/1064

### CODE REVIEW

**Comment by CluEleSsUK** [comment]
Looks good - I think the linter has a few complaints, but once those are fixed I'm happy to approve!

**Comment by Bexanderthebex** [comment]
@CluEleSsUK thanks for taking a look, resolved!

**Review by CluEleSsUK — APPROVED** [review]

**Comment by CluEleSsUK** [comment]
Merged - thanks again for contributing! 🥳

**Comment by Bexanderthebex** [comment]
@CluEleSsUK my pleasure! I’ll try and keep them coming!

**Comment by AnomalRoil** [comment]
Thanks for the contribution 👍🏻  Feel free to also submit a PR to remove it from the website: https://github.com/drand/website
(For example to remove: https://drand.love/docs/overview/#private-randomness)

**Comment by Bexanderthebex** [comment]
@CluEleSsUK @AnomalRoil Done! https://github.com/drand/website/pull/146

**Pull request merged**
