### PR TITLE
refactor: switch to dual MIT + Apache 2.0 license

### PR DESCRIPTION
**Pull request by alanshaw**
This PR switches the project license to using the [Permissive License Stack](https://protocol.ai/blog/announcing-the-permissive-license-stack/) which means that all contributions are available under the most permissive commonly-used licenses, and dependent projects can pick the license that best suits them.

TODO:

* [x] Create contributor sign-off issue https://github.com/drand/drand/issues/280
* [x] Update COPYRIGHT with link to issue https://github.com/drand/drand/pull/259/commits/70bbcba4ec8ed839183908c08c16f2fa81f67ce8

### CODE REVIEW

**Comment by alanshaw** [comment]
I originally removed the copyright notices from the MIT license, do we want to remove them? We removed them in go/js-ipfs when we did the switch e.g. https://github.com/ipfs/go-ipfs/pull/6301/files

**Comment by nikkolasg** [comment]
I'm not an expert in licenses but originally the drand project was hosted and created under the DEDIS umbrella `https://github.com/dedis` and `https://dedis.ch`. If we switch the license now, don't we need to keep the license decided at the time ? What's the point of having a license at all if we can say we now change it ? I'm confused.

**Comment by alanshaw** [comment]
I guess it's not clear whether _this_ is a copy or the original project?

Either way, that's why we need sign-off from the original authors. If we don't get sign-off their contributions remain under the original MIT license.

If while re-licensing we want to remove the copyright notices then my understanding is that it's fine as long as the original authors and contributors consent to it. It's probably less objectionable if we leave the copyright notices in (which is what I've done here) but I don't have strong feels about it.

**Comment by nikkolasg** [comment]
This repo was _moved out_ from the dedis org to the drand org, so it's the original repo

**Comment by jsoares** [comment]
@nikkolasg You can always re-license a project, provided contributors agree. That does not de-license it under the previous licence, i.e. all code published until that moment will forever remain available under both the old and the new licences. In this case, the new licence also includes the old one, so it doesn't really make a difference.

@alanshaw I would default to keeping the copyright notices but it's really just DEDIS; they can easily give a thumbs up or down on that too.

**Comment by alanshaw** [comment]
@nikkolasg are you ok to approve and merge this?

**Pull request merged**
