### PR TITLE
Fix typo in vault

### PR DESCRIPTION
**Pull request by tiennv1997**

### CODE REVIEW

**Review by CluEleSsUK — DISMISSED** [review]

**Comment by CluEleSsUK** [comment]
Hi @tiennv1997 could you possibly sign your commit with PGP? I’ll build it and merge it as soon as you have - many thanks!

**Comment by tiennv1997** [comment]
> Hi @tiennv1997 could you possibly sign your commit with PGP? I’ll build it and merge it as soon as you have - many thanks!

Thanks @CluEleSsUK, I signed commit!

**Comment by AnomalRoil** [comment]
You'll need to sign your past commit using a rebase command, and then do a force push I'm afraid:
```
git rebase --exec 'git commit --amend --no-edit -n -S' HEAD~2
git push --force
```

**Review by AnomalRoil — APPROVED** [review]

**Comment by AnomalRoil** [comment]
Thanks. I'm merging this in our `develop` branch since it is the branch we'll be merging against the `master` one in our next major release.

**Pull request merged**
