### PR TITLE
refactor: store identity base64 encoded

### PR DESCRIPTION
**Pull request by alanshaw**
This PR changes `LoadOrCreatePrivKey` to base64 encode private keys before storage and decode them from base64 when reading them. It also uses `os.MkdirAll` to ensure the directory to write the key file to exists.

It also adds a couple of tests for `LoadOrCreatePrivKey`.

refs #401

BREAKING CHANGE: private keys are now stored base64 encoded. You will need to regenerate or convert any existing private key.

### CODE REVIEW

**Comment by nikkolasg** [comment]
What's the reason to switch to base64 ?

**Comment by Kubuxu** [comment]
So it is easier to distribute them.

**Comment by nikkolasg** [comment]
I need more than "it's easier" to approve this request :D  hex or base64 i dont see right away why it's easier.

**Comment by alanshaw** [comment]
They can be added directly in code and/or infrastructure scripts when encoded. I think IPFS encodes private keys with base64 in config so I guess the choice is familiarity. @hsanjuan it was your request, do you have anything further to add?

**Comment by nikkolasg** [comment]
I'm sorry my bad - i commented even before looking at the changes - i thought you were changing the private key format of drand. 
All good for me then, I'll leave the gossiping things to you :)

**Comment by hsanjuan** [comment]
I would like to request that next time a breaking change happens I get the chance to give a green light before merge:

* First to make sure that I'm aware on how things break
* Second so I get a chance to upgrade the infra without downtime or with minimal impact.
* Third, to potentially push back if the change is problematic, or delay as needed.

**Pull request merged**
