### PR TITLE
using x-forwarded-for in http header

### PR DESCRIPTION
**Pull request by nikkolasg**

### CODE REVIEW

**Comment by willscott** [comment]
This can't always be on - it can otherwise allow a malicious peer to pretend to be anyone else. it needs to be enable-able only when the node is behind a fronting proxy server controlled by the operator that sets it

**Comment by nikkolasg** [comment]
First, it was just a quick update for Hector to try out to read the logs. Sorry I created this as a PR.
But then, it might still be  good idea, given _we are already reading headers_ . It just happens that this is not necessarily the headers we'd like to read from. 
It is true it allows an attacker to pretend to be someone else ... *on the logs* only. Like the crypto part is still gonna check it correctly. It can really be helpful for debugging though.

**Comment by willscott** [comment]
I agree it's useful - we should just have a flag to indicate if the header
can be trusted

**Comment by willscott** [comment]
I looked at this again, and it should be fine since it's only applied to private address space IPs

**Review by willscott — APPROVED** [review]

**Pull request merged**
