### PR TITLE
cover + race together at last

### PR DESCRIPTION
**Pull request by willscott**

### CODE REVIEW

**Comment by alanshaw** [comment]
😢 CI is fail

**Comment by willscott** [comment]
```
--- FAIL: TestBeaconSync (6.61s)

panic: outdated beacon time [recovered]

	panic: outdated beacon time



goroutine 13 [running]:

testing.tRunner.func1.1(0xe015e0, 0xff2fc0)

	/usr/local/go/src/testing/testing.go:940 +0x522

testing.tRunner.func1(0xc000042360)

	/usr/local/go/src/testing/testing.go:943 +0x815

panic(0xe015e0, 0xff2fc0)

	/usr/local/go/src/runtime/panic.go:975 +0x3e3

github.com/drand/drand/beacon.checkWait(0xc00003cba0)

	/go/src/github.com/drand/drand/beacon/handler_test.go:354 +0x1b6

github.com/drand/drand/beacon.TestBeaconSync.func2(0x5, 0x77359400)

	/go/src/github.com/drand/drand/beacon/handler_test.go:381 +0x84

github.com/drand/drand/beacon.TestBeaconSync(0xc000042360)

	/go/src/github.com/drand/drand/beacon/handler_test.go:395 +0x432

testing.tRunner(0xc000042360, 0xf63a10)

	/usr/local/go/src/testing/testing.go:991 +0x231

created by testing.(*T).Run

	/usr/local/go/src/testing/testing.go:1042 +0x6f6

FAIL	github.com/drand/drand/beacon	6.740s

=== RUN   TestClientConstraints
```

**Comment by nikkolasg** [comment]
I mean my only fix is to increase parameters tbh ... (or we go with a >2 vCPU docker !)

**Comment by willscott** [comment]
we can also keep the current setup, but run the code coverage as a secondary workflow so that it isn't required for merging / doesn't double the latency in a noticeable way

**Comment by nikkolasg** [comment]
Or have callbacks at each point in the processing stack of drand but that isn't much desirable either also...

**Pull request closed without merging**
