### PR TITLE
add `drand show ips` subcommand to list IPs of group

### PR DESCRIPTION
**Pull request by willscott**
address #599

### CODE REVIEW

**Comment by willscott** [comment]
> This won't work as intended. This shows the IPs that you want to connect to (inbound), not the IPs that other people will connect from (outbound). This is going to be very confusing and lead to mistakes for some setups (ours). People with whitelist the wrong IPs if they rely on this.
> 
> I would drop this feature altogether to avoid this.

can you think of any utilities we can add to help facilitate sharing of addresses to help people better lock down their network ingress?

**Comment by hsanjuan** [comment]
> > This won't work as intended. This shows the IPs that you want to connect to (inbound), not the IPs that other people will connect from (outbound). This is going to be very confusing and lead to mistakes for some setups (ours). People with whitelist the wrong IPs if they rely on this.
> > I would drop this feature altogether to avoid this.
> 
> can you think of any utilities we can add to help facilitate sharing of addresses to help people better lock down their network ingress?

We can keep this command but instead of querying the group file, it queries a URL where we keep the canonical map of deployment->IP-to-whitelist. We have to think that this map should allow as well for a few extra IPs to be there, like potentially fail-over IPs or backups which are ok to pre-whitelist even if not in use.

We could use IPFS+dnslink to host this list (an easily parseable text file). How does that sound?

**Comment by willscott** [comment]
how do operators set their list of ips they will be using for outbound connections?
how do new group members get pre-added to this list separately from resharing to be added to the group?

**Comment by hsanjuan** [comment]
> how do operators set their list of ips they will be using for outbound connections?
> how do new group members get pre-added to this list separately from resharing to be added to the group?

They come on slack and say "hey, this will be our outbound IPs for whitelisting". Then I take it, do the appropiate verifications and update the list.

I don't see special value in having this as part of the `drand` command either. The place where `drand` runs is not the place that can update your IP whitelisting (which by requirement is a different host at least).

**Comment by willscott** [comment]
closed in favor of https://github.com/drand/drand-allowlist-parse

**Pull request closed without merging**
