### PR TITLE
use genesis seed (original hash) rather than current group hash

### PR DESCRIPTION
**Pull request by willscott**

### CODE REVIEW

**Comment by nikkolasg** [comment]
So I guess it's not the right place to change the name to seed ? :D

**Comment by hsanjuan** [comment]
> So I guess it's not the right place to change the name to seed ? :D

Might as well do that? I mean, we have something called grouphash which is not a group hash anymore? And @alanshaw wanted the json string changed too.

**Comment by hsanjuan** [comment]
ops didn't see it had been merged.

**Comment by willscott** [comment]
@hsanjuan In my mind that is a more dangerous change because we have not tested when clients want that key and it's name has changed. We would need to test that it does not cause clients to get unhappy when they try to deserialize the json. especially now that such client code is in the relays

**Pull request merged**
