### PR TITLE
Store DKG state changes in boltDB

### PR DESCRIPTION
**Pull request by CluEleSsUK**
[x] store DKG state changes in boltDB
[ ] reload the current DKG state (and resume if necessary) on startup
[ ] provide additional CLI tools for introspecting DKG state
[ ] remove any random dkg params from `BeaconProcess`

### CODE REVIEW

**Review by nikkolasg — CHANGES_REQUESTED** [review]
First, I'm really glad the feature of saving the DKG state is coming, that'll save us some uncomfortableness with nodes being restarted at the wrong time. ! 
That being said, I have to say I am feeling quite uneasy at this "Historical context", the fact you are keeping _all_ the dkg states:
* what is exactly the purpose of having historical data ? Would it be really useful to have such data available ? I'm not sure I see the point personnally. Unlike blockchains, we're not tied to keep all historical changes, and we should keep this "liberty" as much as we can.
* Saving DKG state on disk in my view was primarily to allow operators to restart their nodes while waiting on the leader to send the group. For doing that there is no need to keep _all_ historical state, only the _current_ one, and when the DKG is finished, we delete the state.
* Keeping _more_ state is generally more hurtful than useful if it can be avoided, statelessness is often much better and easier to run (think for infra / devops / security - in the sense of more logic = more exposure to panics, weaknesses etc). Same for randomness generation (especially the unchained one) if the only thing the drand node had to keep around was the group file and his key! 
* I can see later down in the PR that you even enforce a node to have all the previous DKGs downloaded to save a new state. That just enforces another constraint on running a drand node to join a network which is not supported by strong reasons, at least currently, and I would even say that can _degrade_ the experience instead of enhancing it.
* Would it be possible to rework this more in the ephemereal spirit: "save DKG state for each state. When DKG finish, delete state." ? In this spirit, I'm also wondering if using the DB for that is the best way, usually meant to keep more long lived data, vs a temp folder but that is more of a taste question I'd say.

**Comment by CluEleSsUK** [comment]
@AnomalRoil and I had some discussion about this on Friday.

My initial plan was to store a history of DKGs in order to ensure to allow nodes that are offline for a period to retrieve their share and recreate past beacons, but Yolan pointed out that keeping all the keyshares over time could pose a security risk - so it's my intention to take out the notion of historical DKGs before this PR is ready.

**Comment by nikkolasg** [comment]
You don't seem to be storing any cryptographic material currently, no shares, so that's why I didn't mention this point.

**Comment by CluEleSsUK** [comment]
Closing this with a view to combining it with the DKG refactor

**Pull request closed without merging**
