### PR TITLE
Updating Readme with Go modules

### LINKED ISSUE #117: Update readme for new instructions to fetch package with go module
Drand uses now go modules but the readme instructions are not updated. I think people should be using `GO111MODULE=on go get ...` otherwise we run into issues like #116 .

### PR DESCRIPTION
**Pull request by AnomalRoil**
Since we are now using Go modules, it seems there are a lot of details that need attention at setup.
This is trying to address them in the Readme.

Fixes #117

### CODE REVIEW

**Comment by nikkolasg** [comment]
Yep, totally right, this readme needs some refreshing. Thanks for putting some work into that !

Let me propose an alternative version: instead of showing the user 2 different choices to install drand, I would just describe one, as the "standard" way to get drand. This will both simplify the instructions for the reader, and the "maintenance" problems as well (i.e. avoiding some questions like "did you install through go modules or not?" ) :D

Please correct me if it's not the case, but on my machine, the simplest thing is to `git clone` and then `go get -u github.com/dedis/drand`. 
**Unfortunately, at the moment** we have to use `go get -u github.com/dedis/drand@master` because there's no module-enabled version of drand yet (because it still fails :/ ). Go module take the last version by default.

What do you think ?

**Comment by AnomalRoil** [comment]
Two questions on my side:
- Do you `git clone` inside of your `GOPATH` or not?
- Do you have the `GO111MODULE` variable  set to `on`?

**Comment by nikkolasg** [comment]
I discovered something else ;) 

I think we could have two ways with different objective (in the meantime that go module's features get better^^):

**We always require GO111MODULE=on**. 
1. **Installation for using drand**: `go get github.com/dedis/drand@master` this installs the drand binary in `$GOPATH/bin` so it is usable.
2. **Downloading drand files for hacking**: `git clone git@github.com:dedis/drand` . After that, you get the source files and all the commands work well with the gomodule enabled.

what do you think ?

**Comment by nikkolasg** [comment]
Yes, I do things always with GOMODULE=on. Now that drand must work with module, I make the full switch ;)
So to answer your first question, outside or inside `$GOPATH` doesn't matter where I clone.

**Comment by AnomalRoil** [comment]
I don't know what's best.

We should definitively have instruction somewhere about how to build it without using `go get`. 
Regarding requiring `GO111MODULE=on`, okay for me.

**Comment by nikkolasg** [comment]
The problem is that with go modules, go get does not download the source files itself anymore it seems, but merely the executable if it is one. Hence my reasoning about "if you just want to use it, just go get" or "if you want to hack on it, git clone it" (as usual when hacking on projects on github!).

**Comment by AnomalRoil** [comment]
@nikkolasg It seems that when using GO111MODULE and `go get` the stuff is downloaded into the `$GOPATH/pkg/mod/github.com/dedis/`

Anyway, I've updated the information in the README. 
Not sure if still necessary now.

**Comment by nikkolasg** [comment]
drand natively uses go module now by default with correct versions. Closing this for now.

**Pull request closed without merging**
