### PR TITLE
Fix burning in the commit ID into the binary

### PR DESCRIPTION
**Pull request by mcamou**

### CODE REVIEW

**Review by willscott — APPROVED** [review]

**Comment by mcamou** [comment]
> Could you please also include this fix? [#956 (comment)](https://github.com/drand/drand/pull/956#discussion_r844856223)

Done, and sorry about that

**Review by AnomalRoil — APPROVED** [review]

**Comment by mcamou** [comment]
@AnomalRoil @willscott I have no idea how to fix the `codecov/patch` error. It's basically saying that the changed line is not covered by tests (which, granted, it isn't, but I'm not sure of the benefit of actually adding a test to exercise that line).

**Comment by willscott** [comment]
that's fine - that's just noting that overall code coverage goes down as a result of this change.

**Comment by mcamou** [comment]
Not sure why it would go down, since the number of Go lines stays the same. Plus, the failing test will not allow me to merge :-(

**Comment by mcamou** [comment]
Thanks... the "Squash and Merge" button was white for me instead of green.

**Pull request merged**
