### PR TITLE
Set version and commit when building on Dockerhub

### PR DESCRIPTION
**Pull request by hsanjuan**
I tested on docker hub and it works

### CODE REVIEW

**Comment by hsanjuan** [comment]
wait, branched off really old commit

**Comment by willscott** [comment]
what system uses this file?

**Comment by hsanjuan** [comment]
Docker hub

**Comment by willscott** [comment]
if we rename the 'gitCommit' environment item to 'SOURCE_COMMIT' it looks like docker hub will have it populated automatically, and likewise, it looks like 'SOURCE_BRANCH' is populated with "the tag being built".

would avoid the extra file potentially https://docs.docker.com/docker-hub/builds/advanced/

if it's preferable, leave a comment in the file to indicate that this is used by docker hub, since the file paths / contents are generic and don't indicate what is using it.

**Comment by hsanjuan** [comment]
you can set source commit but you still have the problem with the version, so I went this way. If you just want the source commit we can switch to env vars.

**Comment by hsanjuan** [comment]
`'SOURCE_BRANCH` is going to be master, or deploy-dev unless a specific tag is built. Not sure how that parses into the version. And is redundant when having the commit?

**Pull request merged**
