### PR TITLE
Updated randomness extractor to use HKDF.

### PR DESCRIPTION
**Pull request by chgorman**

### CODE REVIEW

**Comment by AnomalRoil** [comment]
This should typically be happening at the client level, IMO. Each client can choose to use their own derivation path from the unpredictable, unbiased (in the space of signatures, so in the algebraic group they live in) threshold BLS signatures we are providing.

**Comment by CluEleSsUK** [comment]
Via the client, users receive both the `signature` and the `randomness` presently - clients could use an HKDF on the signature portion to create their own randomness for the properties you described.

Definitely a cool idea, but this would be a huuuuge breaking change to existing drand clients. It'd be cool to have an alternate client implementation that uses an HKDF by default though! 
Our [existing client implementation](https://github.com/drand/drand/tree/master/client) has some cobwebs and it would be cool to have an alternative, updated, external go implementation if you'd be up for it? Would be happy to help along the way of course!

**Comment by chgorman** [comment]
"clients could use an HKDF on the signature portion to create their own randomness for the properties you described": isn't the point of `drand` to allow clients to obtain high-quality randomness **without** needing to worry about the underlying cryptographic primitives? It might be reasonable for those with a background in cryptography to read and understand the HKDF [RFC](https://www.rfc-editor.org/rfc/rfc5869) and [paper](https://eprint.iacr.org/2010/264.pdf) (as well as contributors to this repository who focus on `crypto/`), but this seems like a big ask for the average developer.

I am not currently able to devote a lot of time making an alternative client. I was hoping the upgrade would be an easy fix and a small PR, but alas, I guess not.

If you are not wanting to do any breaking changes right now, then maybe just make a note that **when** breaking changes need to happen (or are planning to happen), look at updating the randomness generation to have a more solid theoretical foundation. If the decision is to go with HKDF, it may be worthwhile to allow for the "context", "length", and "salt" parameters to be exposed as well, but this would require some thought as to what all you want exposed and the added complexity. At the very least, it may be worthwhile to have agreed-upon salt that is first submitted at the beginning of the DKG protocol (somehow) and have that be the salt for HKDF throughout the required time period. This helps ensure that each instantiation is independent; this is discussed more in the [HKDF paper](https://eprint.iacr.org/2010/264.pdf).

**Comment by AnomalRoil** [comment]
This is too big of a breaking change since it would invalidate all past randomness produced using the default method. We will be including alternative derivation path, including an HKDF option in our upcoming "drand-sdk" for developers to use.

**Pull request closed without merging**
