### PR TITLE
return 404 when no beacon hash exists instead of 500

### LINKED ISSUE #1207: API returns 500 instead of 4xx if no beacon handler for chain hash
If a user tries to request a beacon hash that doesn't exist, e.g. `curl api.drand.sh/deadbeefdeadbeef/public/1` returns 500. 
As it's a client error, it should return a 400 or 404
The `/latest` endpoint correctly returns 404, and the functionality should be made consistent

### PR DESCRIPTION
**Pull request by hmcguinn**
Fixes #1207

### CODE REVIEW

**Comment by hmcguinn** [comment]
I'd be happy to add some tests for this behaviour but I'm not super sure where the right place for that is, ``http/server_test.go``?

**Comment by CluEleSsUK** [comment]
Indeed `http/server_test.go` would be the perfect place for the related test.
Many thanks for your contribution! Happy to merge it once you've added a few test cases

**Comment by hmcguinn** [comment]
Added a few tests for the new/current 404 functionality!

I realized I opened this against ``master`` should it be ``develop`` instead?

**Comment by AnomalRoil** [comment]
Making this change against master and cherry-picking it ontop of develop sound good

**Comment by hmcguinn** [comment]
> 

Whoops, missed that. Added

**Review by AnomalRoil — APPROVED** [review]

**Comment by AnomalRoil** [comment]
Could you rebase to sign all of your commits, please?
This should do it:
```
 git rebase --exec 'git commit --amend --no-edit -n -S' HEAD~2
``` 

Once done, we'll deploy it in the coming days so it won't be hitting our HTTP relays immediately. Maybe early next week.

**Review by AnomalRoil — APPROVED** [review]

**Pull request merged**
