### PR TITLE
test: e2e

### PR DESCRIPTION
**Pull request by alanshaw**
🚨 WIP

This PR adds high level e2e tests for various scenarios.

I wanted to be able to easily create new e2e tests for a variety of scenarios where I can see all the commands being run and the order they run in. I wanted the flexibility to start/stop commands at particular points in the test and have the timing of the tests driven by the output of the commands issued (in the same way as would happen if a human operator were issuing the commands).

It's centered around creating "terminal windows" to run commands and then asserting on output (stdout/stderr) to determine if/when a command is successful.

It has the following additional features:

* Output from commands is prefixed with an identifier so you can distinguish between messages when multiple commands are running concurrently.
* All interactions with a running command have a default timeout so if this is run in CI and fails then we'll never stall it for 10 minutes!
* There's a manager to help with the verbosity of dealing with multiple terminals - it allows you to wait for them all to output the same message or wait for them all to successfully exit or kill them all, with a single method call.
* Testing specific terminals and managers - the main implementations return errors when they happen, but if you use `terminal.ForTesting` or `manager.ForTesting` then you get back instances with an equivalent API but instead of methods returning an error, they take a `*testing.T` parameter and call `t.Fatal` when errors occur. This minimizes error handling conditionals in tests to keep them clean.

It includes the following test scenarios:

* [x] DKG success with TLS
* [x] DKG success without TLS
* [x] DKG success when leader terminates `drand share` command
* [x] Resharing to bring a new node into the group
* [x] Resharing to remove a node from the group
* [ ] Follow chain before reshare

### CODE REVIEW

**Comment by nikkolasg** [comment]
Sorry to chim in late but ... from your description, it seems that most of it is already in `demo/` : have you looked at it yet ? in `demo/node/sub_process.go` there is the implementation of an operator that types in the command and has full control over it. The demo already tests multiple scenario with all the right timings etc...
It would be nice to modify `demo/` to add the feature you want instead of adding yet another e2e test that will just increase CI testing time ?

**Comment by alanshaw** [comment]
> Sorry to chim in late but ... from your description, it seems that most of it is already in `demo/` : have you looked at it yet ? in `demo/node/sub_process.go` there is the implementation of an operator that types in the command and has full control over it. The demo already tests multiple scenario (full network takedown, threshold node takedown, catchup, resharing with one node excluded etc) with all the right timings etc...
> It would be nice to modify `demo/` to add the feature you want instead of adding yet another e2e test that will just increase CI testing time ?

Yes, there's definitely overlap here with what's in `demo/`. I did evaluate whether changing it was the way forward but `demo/` didn't align with the goals I had (significantly), so it felt correct to start something new. For clarity, I came across these hurdles:

* Scenarios are not expressed as tests that can be run individually with `go test`.
* It's not obvious to me where the boundaries are between test scenarios.
* It runs like an on-the-rails demonstration of features not a set of discrete end-to-end tests (and given it's name this was probably it's initial purpose(?)).
* I don't know how I'd add a new scenario without altering or in some way effecting existing scenarios.
* In terms of testing, one big long run with every interaction and possible failure makes it difficult to identify:
    * where exactly in the code the failure happened.
    * what was happening at the time of the failure.
    * why a change a developer makes to the code caused the failure.
* ...additionally, accumulated state built up from a big long run makes it more difficult to reason about the system as a whole at any given point. I have to understand all prior state changes to know what the state of the system is now.
* Interactions are not driven by the output of the nodes and so are prone to random failures on slower machines (CI for example). They're also slower to run because of this as we wait for longer than needed before continuing to ensure events have had time to happen.
* The scope is far beyond the black box testing that these e2e tests aim to achieve. `demo/` is verifying files written to disk, that beacons have valid signatures and more. I feel that these kinds of assertions should really be made in a set of focused integration tests, not at this level.
* I can't look at a test scenario and see the commands that need to be run/will be run when the test executes. This makes it harder for me to contribute fixes or new tests as I have to dive deep into the code to understand the process.
* AFAIK only a subset of `demo/` is run in CI and we should be running everything! 😄

This structure I'm proposing for e2e tests eliminates many of these hurdles. I think it'll be much easier to recreate scenarios where failures happen and prevent regressions. I hope it'll be easier to add new tests and maintain existing tests and I hope they'll be more stable and make debugging easier. What do you think? 🙏

**Comment by nikkolasg** [comment]
So first let me answer a few points you raised then suggest two potential way forwards:
> Scenarios are not expressed as tests that can be run individually with go test.

Well, what do you call `demo/demo_test.go` then ? There is one test here that does a DKG, stop a few nodes and then backup, and check beacons all the way. We can make plenty of other such unit tests to test specific scenarios.

> It's not obvious to me where the boundaries are between test scenarios.

The main binary is thought more as a demo that's correct but we can write individual tests with the `Orchestrator` as answered before.

>It runs like an on-the-rails demonstration of features not a set of discrete end-to-end tests (and given it's name this was probably it's initial purpose(?)).

That's correct for the main binary, but as said before it can be ran as well as simple tests.

> I don't know how I'd add a new scenario without altering or in some way effecting existing scenarios.


Just add a new test.

> In terms of testing, one big long run with every interaction and possible failure makes it difficult to identify: 
> where exactly in the code the failure happened.  what was happening at the time of the failure.why a change a developer makes to the code caused the failure.

Sure. I'm happy to break it into smaller parts, it makes sense. But note that from what I see now, due to he way you use the terminal library, you only see if there is not the string you  expected and nothing else, you dont get the logs, and there's yet another big layer of code between drand and what you see as output of the test which may have been the issue in the first place.

> Interactions are not driven by the output of the nodes and so are prone to random failures on slower machines 

As far as I see your code does use a timeout as well. What I'm seeing though is that you are returning directly from as soon as you see the desired output and that's definitely good a feature to have. That being said, I don't think it would be hard to change the `demo/` code to use the `MatchingWriter` so the same principle is used. Also, note that it's not because a node outputs `BEACON_STORED` that the drand node will successfully return it to client. `demo/` is testing from the point of view of a client in this regard.
Also, this feature likely gains some seconds on CI but not much more, since the delay really comes from the period of the beacon itself. We are only inspecting beacons 3s afterwards but we don't delay more than 3s in the end (it doesn't add, if we wait 3 periods we only wait 3periods + 3s maximum).

>The scope is far beyond the black box testing that these e2e tests aim to achieve. demo/ is verifying files written to disk, that beacons have valid signatures and more. 

Demo/ is reading files as a mean to verify the shares are consistent; it could use `drand show share` as well for that. Verifying valid signature is an side effect of verifying there is indeed randomness produced by `drand get` (which verifies the beacon). Demo/ 's goal is to verify the functionality / correctness of a running network from A to Z: creation of the nodes, ceremony,  randomness generation. I'm fine to remove verification of the consistency of shares but it sounds weird to do so just because "it doesn't feel at the right level" (there is a lot of such tests as unit tests in drand anyway already).

> I can't look at a test scenario and see the commands that need to be run/will be run when the test executes.

I actually think that these tests in this PR are harder to comprehend because they are MUCH longer than what demo/ is exposing. Now the meaning of the test is mixed up with all the gritty details of running the commands (the certs, the exacts flags etc). It sounds like testing the CLI si what you want to do here (and it would fit well here).If you want to know what happens when you run DKG, you go look at `Orchestrator.RunDKG` and then `Node.RunDKG`: is it really that difficult ... ?

> AFAIK only a subset of demo/ is run in CI and we should be running everything! smile

CI runs `make test-integration` which runs
```Makefile
test-integration:
	go test -v ./demo
	cd demo && go build && ./demo -build -test -debug
```
So it runs everything.

>  This structure I'm proposing for e2e tests eliminates many of these hurdles. I think it'll be much easier to recreate scenarios where failures happen and prevent regressions. I hope it'll be easier to add new tests and maintain existing tests and I hope they'll be more stable and make debugging easier. What do you think? 

I tend to disagree unfortunately. The only "feature" that I would keep here is reacting directly from the logs. 
* This PR seems to not keep log file nor print them somewhere. It has helped me a lot to inspect logs of individual nodes with their respective timeouts after the test has done. That's what `demo/` is doing currently, write output on file and in case things go wrong, print everything (mostly useful for CI debugging).

* I tend to be on the school of thought of "Try to abstract away as most as possible" and "simplicity is better". This PR goes against both of these dogmas in my opinion.
 - "abstraction": Test now are mixed between individual command line instructions, multiple line of code to give the intent AND the intent. So before to simply run a DKG you needed 3 lines, now you need 60 (TestDKG). 
  - "simplicity": there is a lot of layers now between the test and drand: terminal, testing terminal, multi writer, matching writer etc... And to me the benefit is unclear at the moment.

SO. You already gave a lot of energy into that so I'm feeling bad about saying "don't do this", and I dont want to suffer from the syndrome of "dont touch my code". I can see two ways forwards:
**Integration**: integrate to `demo/` the feature of reacting from the logs directly when it makes sense. And any other feature you'd want to see ?  Like create more separate small tests instead of one big as you were mentioning. 
**Refactoring way**:Go forward with your new API and toolkit but I need to see several features added to it:
 - Ability to see complete logs afterwards somewhere
 - Abstraction for tests, hiding the complexity of the command line flags (or else that would go into the `drand-cli/` test suite!), highlighting the intent of the test rather than the details
 - Re-coding the "long test": that is something important as we need to make sure we test the "real flow" of what we operate: so a node that partcipate in a DKG, then that was down, that caught up the chain and then participate in a resharing should work fine in one flow. Testing each scenario individually has benefits but we need to test them globally as well.

As you can guess I'm much more for the integration way but let's also see what @willscott has to say on this. Even though I can be resisting I'm open to discussion ;)

**Comment by alanshaw** [comment]
> Let me answer first your points and then suggests something:
> 
> > Scenarios are not expressed as tests that can be run individually with go test.
> 
> Well, what do you call `demo/demo_test.go` then ? There is one test here that does a DKG, stop a few nodes and then backup, and check beacons all the way. We can make plenty of other such unit tests to test specific scenarios.

I still don't believe this counts as scenarios I can run individually. It's a big run through in a single test.

> 
> > It's not obvious to me where the boundaries are between test scenarios.
> 
> The main binary is thought more as a demo that's correct but we can write individual tests with the `Orchestrator` as answered before, one already exists in `demo_test.go`.
> 
> > It runs like an on-the-rails demonstration of features not a set of discrete end-to-end tests (and given it's name this was probably it's initial purpose(?)).
> 
> That's correct for the main binary, but as said before it can be ran as well as simple tests.

Yes, I think this is a good idea which is why I'm proposing it in this PR.

> 
> > I don't know how I'd add a new scenario without altering or in some way effecting existing scenarios.
> 
> Just add a new test.

Okay, I mean, just as an example, I find it hard to know what `RunResharing` involves and how I'd alter it to do a scenario where I'm removing a node from the group as opposed to adding one or stop a share command halfway through the process or run it with an incorrect `group.toml`. I could alter that function and it'll get more and more complex or I can add a new one for the specific test. The former makes it more difficult to understand the path of a test and the latter doesn't feel right when it's not used by multiple tests and duplicates code.

> 
> > In terms of testing, one big long run with every interaction and possible failure makes it difficult to identify:
> > where exactly in the code the failure happened.  what was happening at the time of the failure.why a change a developer makes to the code caused the failure.
> 
> Sure. I'm happy to break it into smaller parts, it makes sense. But note that from what I see now, due to he way you use the terminal library, you only see if there is not the string you expected and nothing else, you dont get the logs, and there's yet another big layer of code between drand and what you see as output of the test which may have been the issue in the first place.

I did not know that there were additional logs to get, this is good to know. How do you get them out of CI right now?

I don't agree that there's a big layer of code in between, I tried to keep a balance between it being as minimal as possible and not having super verbose tests.

> As well note that we NEED one big test to make sure we test the real flow the network operates under: a node that participates in a DKG then goes down then does a resharing: that's what real partners are doing so that's what we need to test as well.
> 
> > Interactions are not driven by the output of the nodes and so are prone to random failures on slower machines
> 
> As far as I see your code does use a timeout as well.

No, tests are not driven by timeouts. Every "wait" for output has an timeout (for if the text does not eventually appear and so we don't wait forever) but this is not the same as waiting for an event to happen via a timer.

> What I'm seeing though is that you are returning directly from as soon as you see the desired output and that's definitely good a feature to have.

Thanks! 

> That being said, I don't think it would be hard to change the `demo/` code to use the `MatchingWriter` so the same principle is used.

Great, I'm glad it's easy to use!

> Also, note that it's not because a node outputs `BEACON_STORED` that the drand node will successfully return it to client. `demo/` is testing from the point of view of a client in this regard.

That's great feedback. It would be real easy to address that here - just spin up another terminal to get or watch for a specific value.

> Also, this feature likely gains some seconds on CI but not much more, since the delay really comes from the period of the beacon itself. We are only inspecting beacons 3s afterwards but we don't delay more than 3s in the end (it doesn't add, if we wait 3 periods we only wait 3periods + 3s maximum).

I guess it's hard to judge - the e2e job is taking 1m14s vs 3m55s for `make test-integration` right now.

> 
> > The scope is far beyond the black box testing that these e2e tests aim to achieve. demo/ is verifying files written to disk, that beacons have valid signatures and more.
> 
> Demo/ is reading files as a mean to verify the shares are consistent; it could use `drand show share` as well for that. Verifying valid signature is an side effect of verifying there is indeed randomness produced by `drand get` (which verifies the beacon). Demo/ 's goal is to verify the functionality / correctness of a running network from A to Z: creation of the nodes, ceremony, randomness generation. I'm fine to remove verification of the consistency of shares but it sounds weird to do so just because "it doesn't feel at the right level" (there is a lot of such tests as unit tests in drand anyway already).

I'm not asking `demo/` to change. It does a bunch of things this PR does not and I believe there's value in that. I don't believe it's a good idea to just remove those assertions without a replacement.

My comment about those assertions being at the right level was meant in regard to this PR - I didn't want to do that _here_.

> 
> > I can't look at a test scenario and see the commands that need to be run/will be run when the test executes.
> 
> I actually think that these tests in this PR are harder to comprehend because they are MUCH longer than what demo/ is exposing. Now the meaning of the test is mixed up with all the gritty details of running the commands (the certs, the exacts flags etc).

I think you're super close to this code and are very comfortable with hiding the complexity behind abstractions. I also reckon this is probably some of personal preference and mindset/experience. We could easily abstract some of the common commands here to shorten the tests further.

> It sounds like testing the CLI si what you want to do here (and it would fit well here).

Yeah I was looking to test as closely as possible real world usage.

> If you want to know what happens when you run DKG, you go look at `Orchestrator.RunDKG` and then `Node.RunDKG`:if it's not intuitive enough (...) I m happy to add extra printing to show the commands used. The demo already shows what commands to run to fetch the randomness from the nodes.

The methods the orchestrator has describe an overview of what's being performed. If I look at `Orchestrator.RunDKG` for example I see a loop, a panic channel and calls to `Node.RunDKG` on specific nodes. I then can click through to `Node.RunDKG` which...is an interface but if I find the "subprocess" implementation I can figure it out. This is exactly what I mean by having to dive deep into the code to figure out what the test does and the layers of abstraction that make it more difficult to customise for multiple tests - they work great in the general case but like I said before they'll either get more and more complex for each special case or be duplicated to do something more specific for 1 test.

> 
> > This structure I'm proposing for e2e tests eliminates many of these hurdles. I think it'll be much easier to recreate scenarios where failures happen and prevent regressions. I hope it'll be easier to add new tests and maintain existing tests and I hope they'll be more stable and make debugging easier. What do you think?
> 
> I tend to disagree unfortunately. The only "feature" that I would keep here is reacting directly from the logs.
> 
>     * This PR seems to not keep log file nor print them somewhere. It has helped me a lot to inspect logs of individual nodes with their respective timeouts after the test has done. That's what `demo/` is doing currently, write output on file and in case things go wrong, print everything (mostly useful for CI debugging).

`Stdout` and `Stderr` are printed to the terminal for each command (with a prefix to identify the node) - is this what you're referring to or are there more logs? https://app.circleci.com/pipelines/github/drand/drand/1754/workflows/0247e8fe-aa99-472d-8902-0415cfc37a40/jobs/3627

> 
>     * I tend to be on the school of thought of "Try to abstract away as most as possible" and "simplicity is better". This PR goes against both of these dogmas in my opinion.

🤷‍♂️ I guess we'll agree to disagree.

> 
>     * "abstraction": Test now are mixed between individual command line instructions, multiple line of code to give the intent AND the intent. So before to simply run a DKG you needed 3 lines, now you need 60 (TestDKG).

While I agree in the abstraction for the common case of setup for other tests, having the flexibility is what I was going for here so that we can very easily add more tests for scenarios without having to alter the common case abstractions and potentially disrupt other tests.

> 
>     * "simplicity": there is a lot of layers now between the test and drand: terminal, testing terminal, multi writer, matching writer etc... And to me the benefit is unclear at the moment.

To clarify:

* terminal - just allows you to wait for command outputs
* testing terminal - just a terminal but don't return errors use `t.Fatal`
* matching writer - when something is written, tests to see if it matches the string, if it does, write the match to a channel (this enables waiting for command output)
* multi writer - [`MultiWriter` from `io`](https://golang.org/pkg/io/#MultiWriter) but allows dynamic add/remove of writers (this just allows stdout/stderr from commands to be written to the parent stdout/stderr as well as to matching writer)

> 
> SO. You already gave a lot of energy into that so I'm feeling bad about saying "don't do this", and I dont want to suffer from the syndrome of "dont touch my code". I can see two ways forwards:
> **Integration**: integrate to `demo/` the feature of reacting from the logs directly when it makes sense. And any other feature you'd want to see ? Like create more separate small tests.
> **Refactoring way**:Go forward with your new API and toolkit but I need to see several features added to it:

The important part is the ideas and making testing better. I recognise this overlaps a lot of what `demo/` is doing and this was always going to be a hard sell because of it. I'm not sure it's going to be able to replace `demo/` due to all the extra assertions that it does so perhaps there is only really one option.

**Comment by nikkolasg** [comment]
> Yes, I think this is a good idea which is why I'm proposing it in this PR.

You're proposing much more in this PR than simply adding more individual smaller scope test.

> I did not know that there were additional logs to get, this is good to know. How do you get them out of CI right now?

In case the test fails, it prints all the logs to STDOUT (separated by a clear indicator of which nodes does it belong to).

> I think you're super close to this code and are very comfortable with hiding the complexity behind abstractions. I also reckon this is probably some of personal preference and mindset/experience. We could easily abstract some of the common commands here to shorten the tests further.

Yes - but then how would you abstract things further ? To me it seems like you'd need some kind of an organizer of nodes, and that was the point of having an `Orchestrator`.

> I guess it's hard to judge - the e2e job is taking 1m14s vs 3m55s for make test-integration right now.

Exactly, hard to judge because `make test-integration` is doing different tests with more nodes (in this PR, three nodes with period 2s, in the demo binary + test 6 nodes with period 10s with multiple periods of checking randomness)

> they work great in the general case but like I said before they'll either get more and more complex for each special case or be duplicated to do something more specific for 1 test.

I'm not saying `demo/` is super "flexible" but it is a basis that covers multiple scenarios already. I get the feeling that this PR starts with something complex to be able to do more scenario (which it isn't doing at the moment) so we end up with something _already complex for a simple scenario_ ; which to me feels like we're gonna end up with something even more complex as we do more complex scenarios. I've been to that path of doing things one by one without abstracting before for drand and it quickly ended up as a very long large test. I'm not saying you'll fall into the same traps as me, but it's to me definitely not a good sign forward: I dont believe any code don't change when we ask more out of it.  As a suggestion, by trying _already_ to do a complex scenario (like interrupting in the middle of ceremony), that will surely reveal some of the strengths and weakness of this new toolkit so you can adapt it already to be what it needs to be. 

> I'm not sure it's going to be able to replace demo/ due to all the extra assertions that it does so perhaps there is only really one option.

Well you're selling your PR that it brings a lot of flexibility so it should be able to handle all these "extra assertions" - pun intended ;) -  But I'm fine to remove them as long it makes sense. For example, removing the check on the "share" that each node has at the end: fine you can remove that extra check. Verifying randomness: you have to be able to test the endpoint as a client's perspective so merely curling is not enough (not btw that `demo/` is checking that both HTTP and gRPC are returning the same randomness for the same round: if you remove that extra assertion here, we'd need to add it into `core/` which I agree would be better suited here).

But what's your "one option" then ?  

Again i want to re-iterate that I'm not _against this PR_ **IF** it can fulfill: 
* Ability to see complete logs afterwards somewhere
* Abstraction for tests, hiding the complexity of the command line flags (or else that would go into the drand-cli/ test suite!), highlighting the intent of the test rather than the details.  _One direct consequence of this is that we can start testing for more nodes easily as well (and you want to do that when you reshare)_ without for loops everywhere in the tests (now it's one line per node)
* Re-coding the "long test": that is something important as we need to make sure we test the "real flow" of what we operate: so a node that participate in a DKG, then that was down, that caught up the chain and then participate in a resharing should work fine in one flow. Testing each scenario individually has benefits but we need to test them globally as well.
* Having a binary that just spawns up a new local network that node can play with, as demo/ is doing. I would prefer to remove demo/ entirely, instead of having two packages that does more or less the same thing.

I prefer option of integrating into `demo/` because these are not trivial changes so it's more time and potentially more hard to debug but if you're up for it, I'll be fine with that, it can become the next-gen `demo/`. FWIW, I like the command toolkit you came up with !

**Comment by CluEleSsUK** [comment]
Updated e2e massively - closing this

**Pull request closed without merging**
