### PR TITLE
Update docker image refs

### PR DESCRIPTION
**Pull request by GlacierWalrus**

### CODE REVIEW

**Review by AnomalRoil — DISMISSED** [review]
LGTM. 
You tested all of these files locally with the new images and they seem to work and spin nodes alright?

**Comment by CluEleSsUK** [comment]
hmm I’d be surprised if these work with `tls-disable`

**Comment by AnomalRoil** [comment]
Could you also fix 
https://github.com/drand/drand/blob/1bbc15ae91e50c1f4def0fe94c1834e410b3f206/docker/start-network.sh#L5

?

**Review by AnomalRoil — APPROVED** [review]
I've tried to solve the conflicts and I've removed the --tls-disabled, should be fine now @CluEleSsUK, no?

**Comment by CluEleSsUK** [comment]
lgtm

**Review by CluEleSsUK — APPROVED** [review]

**Comment by GlacierWalrus** [comment]
Meh this is silly and error prone. Should we template this?

**Comment by AnomalRoil** [comment]
Yes, a Github action for updating it upon new tagged release would be best

**Pull request merged**
